### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by rajkumarvoleti** [CodeNode21/SickFits#3]
Hello,
I'm from India. I have taken the "advanced react course" by Webos. But in my package, there were no videos about deploying the site. I have tried different ways but none of them worked. So can you please help me with it? I don't think this is the place to ask it but I think it's better than sending an email. It'll be really great if you can help me. Please let me know if you can.

Rajkumar

**Comment by CodeNode21** [comment]
Hi, there are no videos (as far as I'm aware) explaining deployment. Best place for you to ask questions would be in the slack channel provided to you at sign up. 
Hope this helps

**Comment by rajkumarvoleti** [comment]
Thank you. I'll try that
